from __future__ import annotations

from dataclasses import dataclass


# --- Create-time (compile/validation) ----------------------------------------


PARSE_OK = "PARSE_OK"
PARSE_AMBIGUOUS = "PARSE_AMBIGUOUS"

ERR_UNSUPPORTED_TIMEFRAME = "ERR_UNSUPPORTED_TIMEFRAME"
ERR_UNSUPPORTED_CONDITION = "ERR_UNSUPPORTED_CONDITION"
ERR_TOO_MANY_SYMBOLS = "ERR_TOO_MANY_SYMBOLS"
ERR_INVALID_TIME_WINDOW = "ERR_INVALID_TIME_WINDOW"
ERR_INVALID_NUMBER = "ERR_INVALID_NUMBER"
ERR_MISSING_WHEN = "ERR_MISSING_WHEN"

WARN_DEFAULT_TIMEFRAME_USED = "WARN_DEFAULT_TIMEFRAME_USED"
WARN_DEFAULT_SESSION_USED = "WARN_DEFAULT_SESSION_USED"
WARN_DEFAULT_CONFIRM_USED = "WARN_DEFAULT_CONFIRM_USED"
WARN_EXPIRY_CLAMPED = "WARN_EXPIRY_CLAMPED"


# --- Runtime (evaluation / triggering) ---------------------------------------


SUPPRESS_DATA_STALE = "SUPPRESS_DATA_STALE"
SUPPRESS_DATA_MISSING = "SUPPRESS_DATA_MISSING"
SUPPRESS_INDICATOR_UNAVAILABLE = "SUPPRESS_INDICATOR_UNAVAILABLE"
SUPPRESS_MARKET_CLOSED = "SUPPRESS_MARKET_CLOSED"
SUPPRESS_SESSION_MISMATCH = "SUPPRESS_SESSION_MISMATCH"
SUPPRESS_ENGINE_BUSY = "SUPPRESS_ENGINE_BUSY"
SUPPRESS_RATE_LIMIT = "SUPPRESS_RATE_LIMIT"

SUPPRESS_REGIME = "SUPPRESS_REGIME"
SUPPRESS_CONFIDENCE = "SUPPRESS_CONFIDENCE"
SUPPRESS_COOLDOWN = "SUPPRESS_COOLDOWN"
SUPPRESS_MAX_TRIGGERS_REACHED = "SUPPRESS_MAX_TRIGGERS_REACHED"

NO_TRIGGER_CONDITION_FALSE = "NO_TRIGGER_CONDITION_FALSE"
TRIGGERED_CONDITION_TRUE = "TRIGGERED_CONDITION_TRUE"

DELIVER_OK = "DELIVER_OK"
DELIVER_FAIL_DISCORD = "DELIVER_FAIL_DISCORD"
DELIVER_FAIL_RENDER = "DELIVER_FAIL_RENDER"
DELIVER_DEDUPE_HIT = "DELIVER_DEDUPE_HIT"


@dataclass(frozen=True)
class Reason:
    code: str
    message: str
